site_name: OpenPecha
repo_name: OpenPecha/Toolkit
repo_url: https://github.com/OpenPecha/Toolkit
edit_uri: "blob/master/docs/docs"

theme:
  name: material
  features:
    - search.highlight
    - content.code.annotate
    - navigation.tabs
    - navigation.top

nav:
  - Intro:
    - OpenPecha overview: index.md
  - Data:
    - Introduction: data/introduction.md
    - Download: data/download.md
    - Reference: data/reference.md
    - Background: data/background.md
  - Toolkit:
    - Introduction: toolkit/introduction.md
    - Quickstart: toolkit/quickstart.md
    - Install: toolkit/download.md
    - Reference:
      - reference/00_index.md
      - reference/opf-format.md
      - reference/annotations.md
      - reference/hfml.md
      - reference/pecha.md
      - reference/layer.md
      - reference/metadata.md 
     - Background: toolkit/background.md
  - Community:
    - Community: community.md
  - Benchmarks:
    - Benchmarks: benchmarks.md
    
markdown_extensions:
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - mdx_include:
      base_path: docs
  - admonition
  - codehilite
  - extra
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format ''
  - pymdownx.tabbed

plugins:
  - search
  - mkdocstrings
