site_name: OpenPecha
repo_name: OpenPecha/Toolkit
repo_url: https://github.com/OpenPecha/Toolkit
edit_uri: "blob/master/docs/docs"

theme:
  name: material
  features:
    - search.highlight
    - content.code.annotate
    - navigation.tabs
    - navigation.top

nav:
  - Intro:
    - OpenPecha overview: index.md
  - Data:
    - Introduction: Dataset/introduction.md
    - Download: Dataset/download.md
    - Reference: Dataset/reference.md
    - Background: Dataset/background.md
    - Resources: Dataset/resources.md
  - Toolkit:
    - Introduction: Dataset/introduction.md
    - Download: Dataset/download.md
    - Reference: Dataset/reference.md
      - reference/00_index.md
      - OPF Format: opf-format.md
      - Annotations: annotations.md
      - importers/hfml.md
      - developer/layer.md
      - developer/pecha.md
      - developer/metadata.md  
  - Benchmarks:
    - Background: Dataset/background.md
    - Resources: Dataset/resources.md 
  - Community:
    - OPF Format: opf-format.md
    - Annotations: annotations.md
  - Benchmarks:
    - OPF Format: opf-format.md
    
markdown_extensions:
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - mdx_include:
      base_path: docs
  - admonition
  - codehilite
  - extra
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format ''
  - pymdownx.tabbed

plugins:
  - search
  - mkdocstrings
