site_name: OpenPecha
repo_name: OpenPecha/Toolkit
repo_url: https://github.com/OpenPecha/Toolkit
edit_uri: "blob/master/docs/docs"

theme:
  name: material
  features:
    - search.highlight
    - content.code.annotate
    - navigation.tabs
    - navigation.top
    - navigation.expand

nav:
  - Home:
    - Overview: index.md
  - Data:
    - Intro and download: data/introduction.md
    - Reference:
      - data/opf-format.md
      - data/annotations.md
      - data/hfml.md
    - Background: data/background.md
  - Toolkit:
    - Intro and installation: toolkit/introduction.md
    - Quickstart: toolkit/quickstart.md
    - Reference: toolkot/reference.md
    - Recipies:
      - toolkit/pecha.md
      - toolkit/layer.md
      - toolkit/metadata.md 
    - Background: toolkit/background.md
  - Community:
    - Community: community.md
  - Benchmarks:
    - Benchmarks: benchmarks.md
    
markdown_extensions:
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - mdx_include:
      base_path: docs
  - admonition
  - codehilite
  - extra
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format ''
  - pymdownx.tabbed

plugins:
  - search
  - mkdocstrings
